## @file docker-compose.yml
#  @brief Docker Compose sestava preprocesorů napojených na platformu RIoT.
#  @author Vojtěch Hubáček
#  @defgroup riot_preprocessors RIoT preprocesory
#  @see README.md

services:
  myrta-ndic-preprocessor:
    build:
      context: ./backend
      dockerfile: ndic-preprocessor/Dockerfile
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      NDIC_URL: ${NDIC_URL}
    restart: unless-stopped

  myrta-wazejam-preprocessor:
    build:
      context: ./backend
      dockerfile: wazejam-preprocessor/Dockerfile
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      WAZE_URL: ${WAZE_URL}
    restart: unless-stopped

  myrta-mhd-preprocessor:
    build:
      context: ./backend
      dockerfile: mhd-preprocessor/Dockerfile
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      MHD_WS_URL: ${MHD_WS_URL}
      MHD_GTFS_URL: ${MHD_GTFS_URL}
      MHD_WS_AUTHORIZATION: ${MHD_WS_AUTHORIZATION}
    restart: unless-stopped

networks:
  default:
    external: true
    name: riot_default
