  version: '3'

  services:
    datex-server:
      build:
        context: ./backend
        dockerfile: datex-downloader/Dockerfile
      ports:
        - "8000:8000"
      environment:
        DATEX_USERNAME: ${DATEX_USERNAME}
        DATEX_PASSWORD: ${DATEX_PASSWORD}
      volumes:
        - ./data/ndic_messages:/app/ndic_messages
        - ./data/statistics.json:/app/statistics.json
      restart: unless-stopped

    myrta-ndic-preprocessor:
      build:
        context: ./backend
        dockerfile: ndic-preprocessor/Dockerfile
      environment:
        RABBITMQ_URL: ${RABBITMQ_URL}
        NDIC_URL: ${NDIC_URL}
      restart: unless-stopped

    myrta-wazejam-preprocessor:
      build:
        context: ./backend
        dockerfile: WazeJam_preprocessor/Dockerfile
      environment:
        RABBITMQ_URL: ${RABBITMQ_URL}
        WAZE_URL: ${WAZE_URL}
      restart: unless-stopped

    myrta-mhd-preprocessor:
      build:
        context: ./backend
        dockerfile: mhd-preprocessor/Dockerfile
      environment:
        RABBITMQ_URL: ${RABBITMQ_URL}
        MHD_WS_URL: ${MHD_WS_URL}
        MHD_GTFS_URL: ${MHD_GTFS_URL}
      restart: unless-stopped

  networks:
    default:
      external: true
      name: riot_default