package sharedConstants

const (
	BuiltInFanoutExchangeName                             = "amq.fanout"
	MessageProcessingUnitConnectionNotificationsQueueName = "message-processing-unit-connection-notifications"
	KPIFulfillmentCheckRequestsQueueName                  = "kpi-fulfillment-check-requests"
	KPIFulfillmentCheckResultsQueueName                   = "kpi-fulfillment-check-results"
	RawDataPointQueueName                                 = "raw-data-point"
	SDTypeRegistrationRequestsQueueName                   = "sd-type-registration-requests"
	SDInstanceRegistrationRequestsQueueName               = "sd-instance-registration-requests"
	SetOfSDInstancesUpdatesQueueName                      = "set-of-sd-instances-updates"
	SetOfSDTypesUpdatesQueueName                          = "set-of-sd-types-updates"
	TimeSeriesRawDataQueueName                            = "time-series-raw-data"
	TimeSeriesKPIResultQueueName                          = "time-series-kpi-results"
	TimeSeriesReadRequestQueueName                        = "time-series-read-request"
	TimeSeriesReadCancelRequestQueueName                  = "time-series-read-cancel-request"
	TimeSeriesReadResponseQueueName                       = "time-series-read-response"
	TimeSeriesDistinctTagValuesRequestQueueName           = "time-series-distinct-tag-values-request"
	TimeSeriesDistinctTagValuesResponseQueueName          = "time-series-distinct-tag-values-response"
	TimeSeriesReprocessReadRequestQueueName               = "time-series-reprocess-read-request"
	TimeSeriesReprocessReadResponseQueueName              = "time-series-reprocess-read-response"
	KPIReprocessRequestQueueName                          = "kpi-reprocess-requests"
	TSDBDeleteQueueName                                   = "time-series-delete-requests-tsdb"
	MPUDeleteQueueName                                    = "time-series-delete-requests-mpu"
	KPIConfigUpdateQueueName                              = "kpi-config-update"
)
